apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MESSAGE: "Running smoothly on Kubernetes!"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  API_KEY: "super-secret-devops-key"